insert into STUDY_GUIDE values(1, 'US Capitals');

insert into INDEX_CARD values (1, 'Alabama', 'Montgomery', 1);
insert into INDEX_CARD values (2, 'Alaska', 'Juneau', 1);
insert into INDEX_CARD values (3, 'Arizona', 'Phoenix', 1);
insert into INDEX_CARD values (4, 'Arkansas', 'Little Rock', 1);
insert into INDEX_CARD values (5, 'California', 'Sacramento', 1);
insert into INDEX_CARD values (6, 'Colorado', 'Denver', 1);
insert into INDEX_CARD values (7, 'Connecticut', 'Hartford', 1);
insert into INDEX_CARD values (8, 'Delaware', 'Dover', 1);
insert into INDEX_CARD values (9, 'Florida', 'Tallahassee', 1);
insert into INDEX_CARD values (10, 'Georgia', 'Atlanta', 1);
insert into INDEX_CARD values (11, 'Hawaii', 'Honolulu', 1);
insert into INDEX_CARD values (12, 'Idaho', 'Boise', 1);
insert into INDEX_CARD values (13, 'Illinois', 'Springfield', 1);
insert into INDEX_CARD values (14, 'Indiana', 'Indianapolis', 1);
insert into INDEX_CARD values (15, 'Iowa', 'Des Moines', 1);
insert into INDEX_CARD values (16, 'Kansas', 'Topeka', 1);
insert into INDEX_CARD values (17, 'Kentucky', 'Frankfort', 1);
insert into INDEX_CARD values (18, 'Louisiana', 'Baton Rouge', 1);
insert into INDEX_CARD values (19, 'Maine', 'Augusta', 1);
insert into INDEX_CARD values (20, 'Maryland', 'Annapolis', 1);
insert into INDEX_CARD values (21, 'Massachusetts', 'Boston', 1);
insert into INDEX_CARD values (22, 'Michigan', 'Lansing', 1);
insert into INDEX_CARD values (23, 'Minnesota', 'St. Paul', 1);
insert into INDEX_CARD values (24, 'Mississippi', 'Jackson', 1);
insert into INDEX_CARD values (25, 'Missouri', 'Jefferson City', 1);
insert into INDEX_CARD values (26, 'Montana', 'Helena', 1);
insert into INDEX_CARD values (27, 'Nebraska', 'Lincoln', 1);
insert into INDEX_CARD values (28, 'Nevada', 'Carson City', 1);
insert into INDEX_CARD values (29, 'New Hampshire', 'Concord', 1);
insert into INDEX_CARD values (30, 'New Jersey', 'Trenton', 1);
insert into INDEX_CARD values (31, 'New Mexico', 'Santa Fe', 1);
insert into INDEX_CARD values (32, 'New York', 'Albany', 1);
insert into INDEX_CARD values (33, 'North Carolina', 'Raleigh', 1);
insert into INDEX_CARD values (34, 'North Dakota', 'Bismarck', 1);
insert into INDEX_CARD values (35, 'Ohio', 'Columbus', 1);
insert into INDEX_CARD values (36, 'Oklahoma', 'Oklahoma City', 1);
insert into INDEX_CARD values (37, 'Oregon', 'Salem', 1);
insert into INDEX_CARD values (38, 'Pennsylvania', 'Harrisburg', 1);
insert into INDEX_CARD values (39, 'Rhode Island', 'Providence', 1);
insert into INDEX_CARD values (40, 'South Carolina', 'Columbia', 1);
insert into INDEX_CARD values (41, 'South Dakota', 'Pierre', 1);
insert into INDEX_CARD values (42, 'Tennessee', 'Nashville', 1);
insert into INDEX_CARD values (43, 'Texas', 'Austin', 1);
insert into INDEX_CARD values (44, 'Utah', 'Salt Lake City', 1);
insert into INDEX_CARD values (45, 'Virginia', 'Richmond', 1);
insert into INDEX_CARD values (46, 'Washington', 'Olympia', 1);
insert into INDEX_CARD values (47, 'Vermont', 'Montpelier', 1);
insert into INDEX_CARD values (48, 'West Virginia', 'Charleston', 1);
insert into INDEX_CARD values (49, 'Wisconsin', 'Madison', 1);
insert into INDEX_CARD values (50, 'Wyoming', 'Cheyenne', 1);
