insert into STUDY_GUIDE values(1, 'US Capitals');

insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (1, 'Alabama', 'Montgomery', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (2, 'Alaska', 'Juneau', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (3, 'Arizona', 'Phoenix', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (4, 'Arkansas', 'Little Rock', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (5, 'California', 'Sacramento', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (6, 'Colorado', 'Denver', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (7, 'Connecticut', 'Hartford', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (8, 'Delaware', 'Dover', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (9, 'Florida', 'Tallahassee', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (10, 'Georgia', 'Atlanta', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (11, 'Hawaii', 'Honolulu', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (12, 'Idaho', 'Boise', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (13, 'Illinois', 'Springfield', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (14, 'Indiana', 'Indianapolis', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (15, 'Iowa', 'Des Moines', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (16, 'Kansas', 'Topeka', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (17, 'Kentucky', 'Frankfort', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (18, 'Louisiana', 'Baton Rouge', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (19, 'Maine', 'Augusta', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (20, 'Maryland', 'Annapolis', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (21, 'Massachusetts', 'Boston', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (22, 'Michigan', 'Lansing', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (23, 'Minnesota', 'St. Paul', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (24, 'Mississippi', 'Jackson', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (25, 'Missouri', 'Jefferson City', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (26, 'Montana', 'Helena', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (27, 'Nebraska', 'Lincoln', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (28, 'Nevada', 'Carson City', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (29, 'New Hampshire', 'Concord', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (30, 'New Jersey', 'Trenton', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (31, 'New Mexico', 'Santa Fe', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (32, 'New York', 'Albany', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (33, 'North Carolina', 'Raleigh', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (34, 'North Dakota', 'Bismarck', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (35, 'Ohio', 'Columbus', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (36, 'Oklahoma', 'Oklahoma City', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (37, 'Oregon', 'Salem', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (38, 'Pennsylvania', 'Harrisburg', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (39, 'Rhode Island', 'Providence', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (40, 'South Carolina', 'Columbia', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (41, 'South Dakota', 'Pierre', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (42, 'Tennessee', 'Nashville', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (43, 'Texas', 'Austin', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (44, 'Utah', 'Salt Lake City', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (45, 'Virginia', 'Richmond', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (46, 'Washington', 'Olympia', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (47, 'Vermont', 'Montpelier', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (48, 'West Virginia', 'Charleston', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (49, 'Wisconsin', 'Madison', 1);
insert into INDEX_CARD (index_card_id, front, back, study_guide_id) values (50, 'Wyoming', 'Cheyenne', 1);
